spring:
  application:
    name:online-course-platform

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23licRVNuCy2WdPRAT
            clientSecret: a2f93ef55451fb922d3f17ae8086e35cc991083c
