spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23licRVNuCy2WdPRAT
            clientSecret: a2f93ef55451fb922d3f17ae8086e35cc991083c
            scope: user:email
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
            client-name: GitHub
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
