server:
  port: 8080

logging:
  level:
    org.springframework.security: trace

spring:
  thymeleaf:
    cache: false  # Disable caching for development
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  security:
    oauth2:
      client:
        registration:
          ocp-auth-proxy:
            provider: spring
            client-id: ocp-auth-proxy
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/ocp-auth-proxy
            scope: openid,profile,email
            client-name: OnlineCoursePlatformAuthProxy
          github:
            clientId: Ov23licRVNuCy2WdPRAT
            clientSecret: a2f93ef55451fb922d3f17ae8086e35cc991083c
            scope: user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            client-name: GitHub
        provider:
          spring:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks